def is_valid_docstring(doc : str) -> bool:
    """
    Validate docstring content using minimal quality constraints.
    These prevent placeholder or autogenerated text from entering the dataset.
    """
    if not doc:
        return False
    
    text = doc.strip()

    if len(text) < 20:
        return False
    
    if '.' not in text:
        return False
    
    return True